### ISSUE TITLE
Merge NoCloud support

### ISSUE THREAD

**Issue by ocanty** [vyos/vyos-cloud-init#12]
There is a currently a patch that's been sitting in Phabricator for over a year and forgotten about that adds good NoCloud support to cc_vyos.py

https://phabricator.vyos.net/T1389

Would it be possible for this to be merged in?

**Comment by zdc** [comment]
Hello, @ocanty!

The current implementation of the configuration module for VyOS 1.3 is platform-agnostic and works in all platforms, on which Cloud-init able to provide appropriate configuration options. So, it is not required to add anything specific for NoCloud.

Of course, there may be issues in implementation, thus if you have some specific environment or Metadata and VyOS 1.3 does not able to process them properly, please share details about this in the https://phabricator.vyos.net/ and we will see how to improve this Datasource support.
