### ISSUE TITLE
gateway4 & gateway6 are not being set correctly in network config

### ISSUE THREAD

**Issue by ocanty** [vyos/vyos-cloud-init#13]
https://github.com/vyos/vyos-cloud-init/blob/fd87c24ff8f6f09a7e2cc223a4e8cdb8c08f1ef8/cloudinit/config/cc_vyos.py#L168-L182

There is a scoping issue on L176 & L180, the gateway4 and gateway6 are actually set to the last address in the list of addresses set in L171

I believe the correct code should look like this (similar must be done for gateway6)
`config.set(['protocols', 'static', 'route', '0.0.0.0/0', 'next-hop'], value=iface_config['gateway4'], replace=True)`

**Comment by zdc** [comment]
Thanks, @ocanty! I hope that this was fixed in https://github.com/vyos/vyos-cloud-init/pull/14
